language: node_js
sudo: required
node_js:
  - "11"
services:
  - docker
script:
  - sudo docker build . -t rusttest -f testCoverage.Dockerfile
  - sudo docker create -ti --name dummy rusttest bash
  - sudo docker cp dummy:/code/lcov.info ./
  - sudo docker cp dummy:/code/target ./
  - sudo docker rm -fv dummy
  - bash <(curl -s https://codecov.io/bash) -f lcov.info
  - sudo docker pull lambci/lambda:provided
  - npm ci
  - npm test

before_deploy: 
  - node ./src/js/copyBinaries
  - npm install -g serverless
  - sls deploy

deploy:
  - provider: releases
    api_key: ${github_token}
    file_glob: true
    file:
    - "./credit_faas.zip"
    - "./serverless.yml"
    - "./docs/openapi_merged.yml"
    skip_cleanup: true
    on:
      repo: phillyfan1138/credit_faas
      tags: true