name: release
on:
  push:
    branches:
      master

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run cargo test
      run: cargo test
    - uses: danielhstahl/musl-rust-action@master
    - name: Integration test
      run: |
        docker pull lambci/lambda:provided
        npm ci
        npm test 

    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v5.6
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      id: tag_bump

    - name: deploy aws
      run: |
        node ./src/copyBinaries
        npx serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./docs/*.yml"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag_bump.outputs.new_tag }}
        name: Release ${{ steps.tag_bump.outputs.new_tag }}   
    
    
