name: release
on:
  push:
    branches:
      master

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run cargo test
      run: cargo test
    - uses: phillyfan1138/musl-rust-action@master
    - name: Integration test
      run: |
        docker pull lambci/lambda:provided
        npm ci
        npm test 

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: tag_bump

    - name: deploy aws
      run: |
        node ./src/copyBinaries
        npx serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./docs/*.yml
        tag: ${{ steps.tag_bump.outputs.new_tag }}
        release_name: release ${{ steps.tag_bump.outputs.new_tag }}
        overwrite: true
        file_glob: true

    
    